MACRO (_OS_RELEASE field retval)
    FILE (STRINGS /etc/os-release vars)
    SET (${_value} "${field}-NOTFOUND")
    FOREACH (var ${vars})
        IF (var MATCHES "^${field}=(.*)")
            SET (_value "${CMAKE_MATCH_1}")
            IF (_value MATCHES "^['\"](.*)['\"]\$")
                SET (_value "${CMAKE_MATCH_1}")
            ENDIF ()
            BREAK ()
        ENDIF ()
    ENDFOREACH ()
    SET (${retval} "${_value}")
ENDMACRO (_OS_RELEASE)

IF (EXISTS "/etc/os-release")
    _OS_RELEASE (ID linux_distro_id)
    _OS_RELEASE (VERSION_ID linux_distro_ver)
ENDIF()