###############################################################################
# OpenVAS Vulnerability Test
#
# NatterChat Security Bypass Vulnerability
#
# Authors:
# Antu Sanadi <santu@secpod.com>
#
# Copyright:
# Copyright (c) 2009 SecPod, http://www.secpod.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.901004");
  script_version("2019-05-17T12:32:34+0000");
  script_tag(name:"last_modification", value:"2019-05-17 12:32:34 +0000 (Fri, 17 May 2019)");
  script_tag(name:"creation_date", value:"2009-08-27 13:43:20 +0200 (Thu, 27 Aug 2009)");
  script_tag(name:"cvss_base", value:"7.5");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:P/I:P/A:P");
  script_cve_id("CVE-2008-7047", "CVE-2008-7049");
  script_bugtraq_id(32395, 32385);
  script_name("NatterChat Security Bypass Vulnerability");
  script_xref(name:"URL", value:"http://www.milw0rm.com/exploits/7172");
  script_xref(name:"URL", value:"http://www.milw0rm.com/exploits/7179");
  script_xref(name:"URL", value:"http://xforce.iss.net/xforce/xfdb/46748");
  script_xref(name:"URL", value:"http://xforce.iss.net/xforce/xfdb/46764");

  script_tag(name:"qod_type", value:"remote_banner");
  script_category(ACT_MIXED_ATTACK);
  script_copyright("Copyright (C) 2009 SecPod");
  script_family("Web application abuses");
  script_dependencies("secpod_natterchat_detect.nasl");
  script_require_ports("Services/www", 80);
  script_mandatory_keys("natterchat/detected");

  script_tag(name:"impact", value:"Attackers can exploit this issue to view, add, modify or delete
  information in the back-end database or bypass security restrictions.");

  script_tag(name:"affected", value:"NatterChat version 1.1 on Windows.");

  script_tag(name:"insight", value:"- Vulnerability in the 'home.asp' script that fails to
  adequately secure access to administrative scripts.

  - Multiple SQL injection flaws in login.asp, which can be caused via the
  'txtUsername' parameter and 'txtPassword' parameter in a form generated by home.asp.");

  script_tag(name:"solution", value:"No known solution was made available for at least one year since the disclosure
  of this vulnerability. Likely none will be provided anymore. General solution options are to upgrade to a newer
  release, disable respective features, remove the product or replace the product by another one.");

  script_tag(name:"summary", value:"The host is running NatterChat and is prone to Security Bypass
  vulnerability.");

  script_tag(name:"solution_type", value:"WillNotFix");

  exit(0);
}

include("http_func.inc");
include("version_func.inc");

nchatPort = get_http_port(default:80);

nchatVer = get_kb_item("www/" + nchatPort + "/NatterChat");
nchatVer = eregmatch(pattern:"^(.+) under (/.*)$", string:nchatVer);

if((nchatVer[2] != NULL) && (!safe_checks()))
{
  sndReq = http_get(item:string(nchatVer[2], "/admin/home.asp"),
                    port:nchatPort);
  rcvRes = http_send_recv(port:nchatPort, data:sndReq);

  if("Natterchat Administration - Home" >< rcvRes)
  {
    security_message(nchatPort);
    exit(0);
  }
}

if(nchatVer[1] != NULL)
{
  if(version_is_equal(version:nchatVer[1], test_version:"1.1")){
    security_message(nchatPort);
  }
}
