#!/bin/sh
# Copyright (C) 2010-2018 Greenbone Networks GmbH
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

# Report generator script: results per threat pie plot.
#
# This report generates a PNG graphics file
# with a pie plot of the numbers of threat counts.
# The XML transformation via XSL with xsltproc
# creates a little Python program which uses the pychart
# module to create the pie chart PNG graphics.

SRC=`pwd`
TMP=`mktemp -d` || exit 1

xsltproc ./pieplot.xsl $1 > ${TMP}/pieplot.py 2>${TMP}/xlstproc.err \
 && cd ${TMP} 2>/dev/null \
 && python pieplot.py 2>${TMP}/python.err
