###############################################################################
# OpenVAS Vulnerability Test
# $Id: gb_putty_dll_hijacking_vuln_win.nasl 11900 2018-10-15 07:44:31Z mmartin $
#
# PuTTY DLL Hijacking Vulnerability (Windows)
#
# Authors:
# Rinu Kuriakose <krinu@secpod.com>
#
# Copyright:
# Copyright (C) 2017 Greenbone Networks GmbH, http://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

CPE = "cpe:/a:putty:putty";

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.810541");
  script_version("$Revision: 11900 $");
  script_cve_id("CVE-2016-6167");
  script_tag(name:"cvss_base", value:"4.4");
  script_tag(name:"cvss_base_vector", value:"AV:L/AC:M/Au:N/C:P/I:P/A:P");
  script_tag(name:"last_modification", value:"$Date: 2018-10-15 09:44:31 +0200 (Mon, 15 Oct 2018) $");
  script_tag(name:"creation_date", value:"2017-02-09 14:25:24 +0530 (Thu, 09 Feb 2017)");
  script_tag(name:"qod_type", value:"registry");
  script_name("PuTTY DLL Hijacking Vulnerability (Windows)");

  script_tag(name:"summary", value:"The host is installed with PuTTY and is
  prone to dll hijacking vulnerability.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable version is present on the target host.");

  script_tag(name:"insight", value:"The flaw is due to multiple untrusted search
  path errors.");

  script_tag(name:"impact", value:"Successful exploitation will allow remote
  attackers to execute arbitrary code in the context of the affected application.
  Failed exploit attempts will result in a denial of service condition.");

  script_tag(name:"affected", value:"PuTTY beta 0.67(Windows installers
  created by Inno Setup for version 0.67) on Windows.");

  script_tag(name:"solution", value:"Upgrade to PuTTY version 0.67 or later
  (MSI format for PuTTY's Windows installer (generated by the WiX toolset)).");

  script_tag(name:"solution_type", value:"VendorFix");

  script_xref(name:"URL", value:"https://packetstormsecurity.com/files/137742");
  script_xref(name:"URL", value:"http://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html");
  script_copyright("Copyright (C) 2017 Greenbone Networks GmbH");
  script_category(ACT_GATHER_INFO);
  script_family("General");
  script_dependencies("gb_putty_portable_detect.nasl");
  script_require_ports(139, 445);
  script_mandatory_keys("putty/version");

  script_xref(name:"URL", value:"http://www.chiark.greenend.org.uk/~sgtatham/putty");
  exit(0);
}

include("smb_nt.inc");
include("host_details.inc");
include("version_func.inc");
include("secpod_smb_func.inc");

if(!puttyVer = get_app_version(cpe:CPE)){
  exit(0);
}

os_arch = get_kb_item("SMB/Windows/Arch");
if(!os_arch){
  exit(0);
}

## Only installer created by Inno Setup are vulnerable and Inno Setup
## creates the following keys.
## http://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html?
if("x86" >< os_arch){
  key = "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PuTTY_is1";
}

else if("x64" >< os_arch){
  key =  "SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\PuTTY_is1";
}

if(version_is_equal(version:puttyVer, test_version:"0.67"))
{
  inLocation = registry_get_sz(key:key,item:"Inno Setup: App Path");
  if(!inLocation){
    exit(0);
  }

  report = report_fixed_ver(installed_version:puttyVer, fixed_version:"0.67 (MSI format for PuTTY's Windows installer)");
  security_message(data:report);
  exit(0);
}

exit(99);