.TH database-statistics-sqlite 8 User Manuals
.SH NAME
database-statistics-sqlite \- Collect stats for GVM database
.SH SYNOPSIS
\fBdatabase-statistics-sqlite DATABASE
\f1
.SH DESCRIPTION
Collect statistics for a Greenbone Vulnerability Manager SQLite DATABASE. 
.SH SEE ALSO
\fBgvmd(8)\f1
.SH MORE INFORMATION ABOUT THE OPENVAS PROJECT
The canonical places where you will find more information about the OpenVAS project are: \fBhttp://www.openvas.org/\f1 (Official site) \fBhttp://wald.intevation.org/projects/openvas/\f1 (Development Platform) 
.SH COPYRIGHT
The Greenbone Vulnerability Manager is released under the GNU GPL, version 2, or, at your option, any later version. 
