###############################################################################
# OpenVAS Vulnerability Test
# $Id: gb_cloudbees_jenkins_winstone_xss_vuln_aug16_lin.nasl 12761 2018-12-11 14:32:20Z cfischer $
#
# Jenkins Winstone Servlet Cross Site Scripting Vulnerability August16 (Linux)
#
# Authors:
# Rinu Kuriakose <krinu@secpod.com>
#
# Copyright:
# Copyright (C) 2016 Greenbone Networks GmbH, http://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

CPE = "cpe:/a:jenkins:jenkins";

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.808277");
  script_version("$Revision: 12761 $");
  script_cve_id("CVE-2011-4344");
  script_bugtraq_id(52384);
  script_tag(name:"cvss_base", value:"2.6");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:H/Au:N/C:N/I:P/A:N");
  script_tag(name:"last_modification", value:"$Date: 2018-12-11 15:32:20 +0100 (Tue, 11 Dec 2018) $");
  script_tag(name:"creation_date", value:"2016-08-04 13:00:09 +0530 (Thu, 04 Aug 2016)");
  script_name("Jenkins Winstone Servlet Cross Site Scripting Vulnerability August16 (Linux)");

  script_tag(name:"summary", value:"This host is installed with CloudBees
  Jenkins and is prone to a cross-site scripting vulnerability.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable version is present on the target host.");

  script_tag(name:"insight", value:"The flaw is due to an insufficient input
  validation error in 'winstone' servlet container that Jenkins runs in when
  running in standalone mode.");

  script_tag(name:"impact", value:"Successful exploitation will allow remote
  attackers to embed malicious JavaScript into pages generated by Jenkins.");

  script_tag(name:"affected", value:"CloudBees Jenkins 1.409 LTS before 1.409.3 LTS
  on Linux");

  script_tag(name:"solution", value:"Upgrade to CloudBees Jenkins LTS 1.409.3 or
  later.");

  script_tag(name:"solution_type", value:"VendorFix");

  script_tag(name:"qod_type", value:"remote_banner_unreliable");

  script_xref(name:"URL", value:"https://www.cloudbees.com/jenkins-security-advisory-2011-11-08");

  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2016 Greenbone Networks GmbH");
  script_family("Web application abuses");
  script_dependencies("sw_jenkins_detect.nasl", "os_detection.nasl");
  script_mandatory_keys("jenkins/installed", "Host/runs_unixoide");
  script_require_ports("Services/www", 8080);
  exit(0);
}


include("host_details.inc");
include("version_func.inc");

if(!jenkinPort = get_app_port(cpe:CPE)){
  exit(0);
}

if(!jenkinVer = get_app_version(cpe:CPE, port:jenkinPort)){
  exit(0);
}

if(version_in_range(version:jenkinVer, test_version:"1.409", test_version2:"1.409.2"))
{
  report = report_fixed_ver(installed_version:jenkinVer, fixed_version:"1.409.3");
  security_message(data:report, port:jenkinPort);
  exit(0);
}
