###############################################################################
# OpenVAS Vulnerability Test
# $Id: gb_nmap_smb_psexec_net.nasl 12127 2018-10-26 13:14:31Z cfischer $
#
# Autogenerated NSE wrapper
#
# Authors:
# NSE-Script: Ron Bowes
# NASL-Wrapper: autogenerated
#
# Copyright:
# NSE-Script: The Nmap Security Scanner (http://nmap.org)
# Copyright (C) 2011 Greenbone Networks GmbH, http://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.104148");
  script_version("$Revision: 12127 $");
  script_tag(name:"last_modification", value:"$Date: 2018-10-26 15:14:31 +0200 (Fri, 26 Oct 2018) $");
  script_tag(name:"creation_date", value:"2011-06-01 16:32:46 +0200 (Wed, 01 Jun 2011)");
  script_tag(name:"cvss_base", value:"4.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:S/C:P/I:N/A:N");
  script_name("Nmap NSE net: smb-psexec");
  script_category(ACT_INIT);
  script_tag(name:"qod_type", value:"remote_analysis");
  script_copyright("NSE-Script: The Nmap Security Scanner; NASL-Wrapper: Greenbone Networks GmbH");
  script_family("Nmap NSE net");
  script_dependencies("nmap_nse_net.nasl");
  script_mandatory_keys("Tools/Launch/nmap_nse_net");

  script_add_preference(name:"randomseed", value:"", type:"entry");
  script_add_preference(name:"str", value:"", type:"entry");
  script_add_preference(name:"nocipher", value:"", type:"entry");
  script_add_preference(name:"nocleanup", value:"", type:"entry");
  script_add_preference(name:"share", value:"", type:"entry");
  script_add_preference(name:"sharepath", value:"", type:"entry");
  script_add_preference(name:"smbport", value:"", type:"entry");
  script_add_preference(name:"nohide", value:"", type:"entry");
  script_add_preference(name:"key", value:"", type:"entry");
  script_add_preference(name:"time", value:"", type:"entry");
  script_add_preference(name:"smbbasic", value:"", type:"entry");
  script_add_preference(name:"smbsign", value:"", type:"entry");
  script_add_preference(name:"config", value:"", type:"entry");
  script_add_preference(name:"cleanup", value:"", type:"entry");

  script_tag(name:"summary", value:"This script implements remote process execution similar to the
Sysinternals' psexec tool, allowing a user to run a series of programs on a
remote machine and read the output. This is great for gathering information
about servers, running the same tool on a range of  system, or even
installing a backdoor on a collection of computers.

SYNTAX:

randomseed:    Set to a value to change the filenames/service names that are
randomly generated.

str:     The string go cipher/uncipher.

nocipher:  Set to '1' or 'true' to disable the ciphering of the returned text
(useful for debugging).

nocleanup:  If set to '1' or 'true', don't clean up at all. This leaves the
files on the remote system and the wrapper service installed.

share:    Set to override the share used for uploading. This also stops shares
from being enumerated, and all other shares will be ignored. No checks are done
to determine whether or not this is a valid share before using it. Requires
'sharepath' to be set.

sharepath:  The full path to the share (eg, 'c:\windows'). This is required when creating a service.

smbport:       Override the default port choice. If 'smbport' is open, it's used. It's assumed
to be the same protocol as port 445, not port 139.

nohide:   Don't set the uploaded files to hidden/system/etc.

key:      Script uses this value instead of a random encryption key (useful for debugging the crypto).

time:     The minimum amount of time, in seconds, to wait for the external module to finish (default:'15')

smbbasic:     Forces the authentication to use basic security, as opposed to 'extended security'.
Against most modern systems, extended security should work, but there may be cases
where you want to force basic. There's a chance that you'll get better results for
enumerating users if you turn on basic authentication.

smbsign:       Controls whether or not server signatures are checked in SMB packets. By default, on Windows,
server signatures aren't enabled or required. By default, this library will always sign
packets if it knows how, and will check signatures if the server says to. Possible values are:

  - 'force':      Always check server signatures, even if server says it doesn't support them (will
probably fail, but is technically more secure).

  - 'negotiate': [default] Use signatures if server supports them.

  - 'ignore':    Never check server signatures. Not recommended.

  - 'disable':   Don't send signatures, at all, and don't check the server's. not recommended.

config:  The config file for this host (stores the encryption key).

cleanup:  Set to '1' or 'true' to simply clean up any mess we made (leftover
files, processes, etc. on the host OS).");

  script_tag(name:"solution_type", value:"Mitigation");

  exit(0);
}

include("nmap.inc");

# The corresponding NSE script doesn't belong to the 'safe' category
if (safe_checks()) exit(0);

phase = 0;
if (defined_func("scan_phase")) {
  phase = scan_phase();
}

if (phase == 1) {
    argv = make_array();

    pref = script_get_preference("randomseed");
    if (!isnull(pref) && pref != "") {
        argv["randomseed"] = string('"', pref, '"');
    }
    pref = script_get_preference("str");
    if (!isnull(pref) && pref != "") {
        argv["str"] = string('"', pref, '"');
    }
    pref = script_get_preference("nocipher");
    if (!isnull(pref) && pref != "") {
        argv["nocipher"] = string('"', pref, '"');
    }
    pref = script_get_preference("nocleanup");
    if (!isnull(pref) && pref != "") {
        argv["nocleanup"] = string('"', pref, '"');
    }
    pref = script_get_preference("share");
    if (!isnull(pref) && pref != "") {
        argv["share"] = string('"', pref, '"');
    }
    pref = script_get_preference("sharepath");
    if (!isnull(pref) && pref != "") {
        argv["sharepath"] = string('"', pref, '"');
    }
    pref = script_get_preference("smbport");
    if (!isnull(pref) && pref != "") {
        argv["smbport"] = string('"', pref, '"');
    }
    pref = script_get_preference("nohide");
    if (!isnull(pref) && pref != "") {
        argv["nohide"] = string('"', pref, '"');
    }
    pref = script_get_preference("key");
    if (!isnull(pref) && pref != "") {
        argv["key"] = string('"', pref, '"');
    }
    pref = script_get_preference("time");
    if (!isnull(pref) && pref != "") {
        argv["time"] = string('"', pref, '"');
    }
    pref = script_get_preference("smbbasic");
    if (!isnull(pref) && pref != "") {
        argv["smbbasic"] = string('"', pref, '"');
    }
    pref = script_get_preference("smbsign");
    if (!isnull(pref) && pref != "") {
        argv["smbsign"] = string('"', pref, '"');
    }
    pref = script_get_preference("config");
    if (!isnull(pref) && pref != "") {
        argv["config"] = string('"', pref, '"');
    }
    pref = script_get_preference("cleanup");
    if (!isnull(pref) && pref != "") {
        argv["cleanup"] = string('"', pref, '"');
    }
    nmap_nse_register(script:"smb-psexec", args:argv);
} else if (phase == 2) {
    res = nmap_nse_get_results(script:"smb-psexec");
    foreach portspec (keys(res)) {
        output_banner = 'Result found by Nmap Security Scanner (smb-psexec.nse) http://nmap.org:\n\n';
        if (portspec == "0") {
            security_message(data:output_banner + res[portspec], port:0);
        } else {
            v = split(portspec, sep:"/", keep:0);
            proto = v[0];
            port = v[1];
            security_message(data:output_banner + res[portspec], port:port, protocol:proto);
        }
    }
}
