###############################################################################
# OpenVAS Vulnerability Test
#
# RedHat Update for samba4 RHSA-2013:0506-02
#
# Authors:
# System Generated Check
#
# Copyright:
# Copyright (c) 2013 Greenbone Networks GmbH, http://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# (or any later version), as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

if(description)
{
  script_xref(name:"URL", value:"https://www.redhat.com/archives/rhsa-announce/2013-February/msg00049.html");
  script_oid("1.3.6.1.4.1.25623.1.0.870935");
  script_version("$Revision: 12497 $");
  script_tag(name:"last_modification", value:"$Date: 2018-11-23 09:28:21 +0100 (Fri, 23 Nov 2018) $");
  script_tag(name:"creation_date", value:"2013-02-22 10:02:23 +0530 (Fri, 22 Feb 2013)");
  script_cve_id("CVE-2012-1182");
  script_bugtraq_id(52973);
  script_tag(name:"cvss_base", value:"10.0");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:L/Au:N/C:C/I:C/A:C");
  script_name("RedHat Update for samba4 RHSA-2013:0506-02");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'samba4'
  package(s) announced via the referenced advisory.");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (c) 2013 Greenbone Networks GmbH");
  script_family("Red Hat Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/rhel", "ssh/login/rpms", re:"ssh/login/release=RHENT_6");
  script_tag(name:"affected", value:"samba4 on Red Hat Enterprise Linux Desktop (v. 6),
  Red Hat Enterprise Linux Server (v. 6),
  Red Hat Enterprise Linux Workstation (v. 6)");
  script_tag(name:"solution", value:"Please Install the Updated Packages.");
  script_tag(name:"insight", value:"Samba is an open-source implementation of the Server Message Block (SMB) or
  Common Internet File System (CIFS) protocol, which allows PC-compatible
  machines to share files, printers, and other information.

  A flaw was found in the Samba suite's Perl-based DCE/RPC IDL (PIDL)
  compiler, used to generate code to handle RPC calls. This could result in
  code generated by the PIDL compiler to not sufficiently protect against
  buffer overflows. (CVE-2012-1182)

  The samba4 packages have been upgraded to upstream version 4.0.0, which
  provides a number of bug fixes and enhancements over the previous version.
  In particular, improved interoperability with Active Directory (AD)
  domains. SSSD now uses the libndr-krb5pac library to parse the Privilege
  Attribute Certificate (PAC) issued by an AD Key Distribution Center (KDC).

  The Cross Realm Kerberos Trust functionality provided by Identity
  Management, which relies on the capabilities of the samba4 client library,
  is included as a Technology Preview. This functionality and server
  libraries, is included as a Technology Preview. This functionality uses the
  libndr-nbt library to prepare Connection-less Lightweight Directory Access
  Protocol (CLDAP) messages.

  Additionally, various improvements have been made to the Local Security
  Authority (LSA) and Net Logon services to allow verification of trust
  from a Windows system. Because the Cross Realm Kerberos Trust functionality
  is considered a Technology Preview, selected samba4 components are
  considered to be a Technology Preview. For more information on which Samba
  packages are considered a Technology Preview, refer to Table 5.1, Samba4
  Package Support in the Release Notes, linked to from the References.
  (BZ#766333, BZ#882188)

  This update also fixes the following bug:

  * Prior to this update, if the Active Directory (AD) server was rebooted,
  Winbind sometimes failed to reconnect when requested by wbinfo -n or
  wbinfo -s commands. Consequently, looking up users using the wbinfo tool
  failed. This update applies upstream patches to fix this problem and now
  looking up a Security Identifier (SID) for a username, or a username for a
  given SID, works as expected after a domain controller is rebooted.
  (BZ#878564)

  All users of samba4 are advised to upgrade to these updated packages,
  which fix these issues and add these enhancements.

  Warning: If you upgrade from Red Hat Enterprise Linux 6.3 to Red Hat
  Enterprise Linux 6.4 and you have Samba in use, you should make sure that
  you uninstall the package named samba4 to avoid conflicts during the
  upgrade.");
  script_tag(name:"qod_type", value:"package");
  script_tag(name:"solution_type", value:"VendorFix");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release) exit(0);

res = "";

if(release == "RHENT_6")
{

  if ((res = isrpmvuln(pkg:"samba4", rpm:"samba4~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-client", rpm:"samba4-client~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-common", rpm:"samba4-common~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-dc", rpm:"samba4-dc~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-dc-libs", rpm:"samba4-dc-libs~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-debuginfo", rpm:"samba4-debuginfo~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-devel", rpm:"samba4-devel~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-libs", rpm:"samba4-libs~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-pidl", rpm:"samba4-pidl~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-python", rpm:"samba4-python~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-swat", rpm:"samba4-swat~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-test", rpm:"samba4-test~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-winbind", rpm:"samba4-winbind~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-winbind-clients", rpm:"samba4-winbind-clients~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if ((res = isrpmvuln(pkg:"samba4-winbind-krb5-locator", rpm:"samba4-winbind-krb5-locator~4.0.0~55.el6.rc4", rls:"RHENT_6")) != NULL)
  {
    security_message(data:res);
    exit(0);
  }

  if (__pkg_match) exit(99);
  exit(0);
}
