###############################################################################
# OpenVAS Vulnerability Test
# $Id: GSHB_depend.inc 9015 2018-03-02 15:20:47Z emoss $
#
# These are the requirements for IT-Grundschutz Kompendium, which we
# should include in our tests
#
# Authors:
# Emanuel Moss <emanuel.moss@greenbone.net
#
# Copyright:
# Copyright (C) 2018 Greenbone Networks GmbH, https://www.greenbone.net
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
###############################################################################

depend= make_list(
  'SYS.1.2.2.A1',
  'SYS.1.2.2.A2',
  'SYS.1.2.2.A3',
  'SYS.1.2.2.A4',
  'SYS.1.2.2.A5',
  'SYS.1.2.2.A6',
  'SYS.1.2.2.A7',
  'SYS.1.2.2.A8',
  'SYS.1.2.2.A9',
  'SYS.1.2.2.A10',
  'SYS.1.2.2.A11',
  'SYS.1.2.2.A12',
  'SYS.1.2.2.A13',
  'SYS.1.2.2.A14',
  'SYS.1.3.A1',
  'SYS.1.3.A2',
  'SYS.1.3.A3',
  'SYS.1.3.A4',
  'SYS.1.3.A5',
  'SYS.1.3.A6',
  'SYS.1.3.A7',
  'SYS.1.3.A8',
  'SYS.1.3.A9',
  'SYS.1.3.A10',
  'SYS.1.3.A11',
  'SYS.1.3.A12',
  'SYS.1.3.A13',
  'SYS.1.3.A14',
  'SYS.1.3.A15',
  'SYS.1.3.A16',
  'SYS.1.3.A17',
  'SYS.2.2.2.A1',
  'SYS.2.2.2.A2',
  'SYS.2.2.2.A3',
  'SYS.2.2.2.A4',
  'SYS.2.2.2.A5',
  'SYS.2.2.2.A6',
  'SYS.2.2.2.A7',
  'SYS.2.2.2.A8',
  'SYS.2.2.2.A9',
  'SYS.2.2.2.A10',
  'SYS.2.2.2.A11',
  'SYS.2.2.2.A12',
  'SYS.2.2.2.A13',
  'SYS.2.2.2.A14',
  'SYS.2.2.2.A15',
  'SYS.2.2.2.A16',
  'SYS.2.2.2.A17',
  'SYS.2.2.2.A18',
  'SYS.2.2.2.A19',
  'SYS.2.2.2.A20',
  'SYS.2.2.2.A21',
  'SYS.2.2.3.A1',
  'SYS.2.2.3.A2',
  'SYS.2.2.3.A3',
  'SYS.2.2.3.A4',
  'SYS.2.2.3.A5',
  'SYS.2.2.3.A6',
  'SYS.2.2.3.A7',
  'SYS.2.2.3.A8',
  'SYS.2.2.3.A9',
  'SYS.2.2.3.A10',
  'SYS.2.2.3.A11',
  'SYS.2.2.3.A12',
  'SYS.2.2.3.A13',
  'SYS.2.2.3.A14',
  'SYS.2.2.3.A15',
  'SYS.2.2.3.A16',
  'SYS.2.2.3.A17',
  'SYS.2.2.3.A18',
  'SYS.2.2.3.A19',
  'SYS.2.2.3.A20',
  'SYS.2.2.3.A21',
  'SYS.2.2.3.A22',
  'SYS.2.2.3.A23',
  'SYS.2.2.3.A24',
  'SYS.2.2.3.A25',
  'SYS.2.3.A1',
  'SYS.2.3.A2',
  'SYS.2.3.A3',
  'SYS.2.3.A4',
  'SYS.2.3.A5',
  'SYS.2.3.A6',
  'SYS.2.3.A7',
  'SYS.2.3.A8',
  'SYS.2.3.A9',
  'SYS.2.3.A10',
  'SYS.2.3.A11',
  'SYS.2.3.A12',
  'SYS.2.3.A13',
  'SYS.2.3.A14',
  'SYS.2.3.A15',
  'SYS.2.3.A16',
  'SYS.2.3.A17',
  'SYS.2.3.A18',
  'SYS.2.3.A19',
  'SYS.2.3.A20'
);

