#!/bin/sh
#
# GVM
# $Id$
# Description: Report generator script: IVIL.
#
# This report generator creates a single IVIL
# file from the XML report using a XSL transformation
# with the tool xsltproc.
#
# Authors:
# Tim Brown <timb@openvas.org>
#
# Copyright:
# Copyright (C) 2010 Tim Brown
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2,
# or, at your option, any later version as published by the Free
# Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

xsltproc ./IVIL.xsl $1
