# Copyright (C) 2020 Greenbone Networks GmbH
# Text descriptions are largely excerpted from the referenced
# advisory, and are Copyright (C) the respective author(s)
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

if(description)
{
  script_oid("1.3.6.1.4.1.25623.1.0.853026");
  script_version("2020-02-06T07:28:53+0000");
  script_cve_id("CVE-2018-11243", "CVE-2019-1010048", "CVE-2019-14296", "CVE-2019-20021", "CVE-2019-20053");
  script_tag(name:"cvss_base", value:"6.8");
  script_tag(name:"cvss_base_vector", value:"AV:N/AC:M/Au:N/C:P/I:P/A:P");
  script_tag(name:"last_modification", value:"2020-02-06 07:28:53 +0000 (Thu, 06 Feb 2020)");
  script_tag(name:"creation_date", value:"2020-02-05 04:01:14 +0000 (Wed, 05 Feb 2020)");
  script_name("openSUSE: Security Advisory for upx (openSUSE-SU-2020:0163-1)");
  script_category(ACT_GATHER_INFO);
  script_copyright("Copyright (C) 2020 Greenbone Networks GmbH");
  script_family("SuSE Local Security Checks");
  script_dependencies("gather-package-list.nasl");
  script_mandatory_keys("ssh/login/suse", "ssh/login/rpms", re:"ssh/login/release=openSUSELeap15\.1");

  script_xref(name:"URL", value:"http://lists.opensuse.org/opensuse-security-announce/2020-02/msg00003.html");

  script_tag(name:"summary", value:"The remote host is missing an update for the 'upx'
  package(s) announced via the openSUSE-SU-2020:0163-1 advisory.");

  script_tag(name:"vuldetect", value:"Checks if a vulnerable package version is present on the target host.");

  script_tag(name:"insight", value:"This update for upx to version 3.96 fixes the following issues:


  - CVE-2019-1010048: Fixed a denial of service in
  PackLinuxElf32::PackLinuxElf32help1() (boo#1141777).

  - CVE-2019-14296: Fixed a denial of service in canUnpack() (boo#1143839).

  - CVE-2019-20021: Fixed a heap-based buffer over-read in canUnpack()
  (boo#1159833).

  - CVE-2019-20053: Fixed a denial of service in canUnpack() (boo#1159920).

  - CVE-2018-11243: Fixed a denial of service in PackLinuxElf64::unpack()
  (boo#1094138).

  - Update to version 3.96

  * Bug fixes: [CVE-2019-1010048, boo#1141777] [CVE-2019-14296,
  boo#1143839] [CVE-2019-20021, boo#1159833] [CVE-2019-20053,
  boo#1159920] [CVE-2018-11243 partially - ticket 206 ONLY, boo#1094138]

  - Update to version 3.95

  * Flag --force-pie when ET_DYN main program is not marked as DF_1_PIE

  * Better compatibility with varying layout of address space on Linux

  * Support for 4 PT_LOAD layout in ELF generated by binutils-2.31

  * bug fixes, particularly better diagnosis of malformed input


  Patch Instructions:

  To install this openSUSE Security Update use the SUSE recommended
  installation methods
  like YaST online_update or 'zypper patch'.

  Alternatively you can run the command listed for your product:

  - openSUSE Leap 15.1:

  zypper in -t patch openSUSE-2020-163=1");

  script_tag(name:"affected", value:"'upx' package(s) on openSUSE Leap 15.1.");

  script_tag(name:"solution", value:"Please install the updated package(s).");

  script_tag(name:"solution_type", value:"VendorFix");
  script_tag(name:"qod_type", value:"package");

  exit(0);
}

include("revisions-lib.inc");
include("pkg-lib-rpm.inc");

release = rpm_get_ssh_release();
if(!release)
  exit(0);

res = "";
report = "";

if(release == "openSUSELeap15.1") {

  if(!isnull(res = isrpmvuln(pkg:"upx", rpm:"upx~3.96~lp151.3.3.1", rls:"openSUSELeap15.1"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"upx-debuginfo", rpm:"upx-debuginfo~3.96~lp151.3.3.1", rls:"openSUSELeap15.1"))) {
    report += res;
  }

  if(!isnull(res = isrpmvuln(pkg:"upx-debugsource", rpm:"upx-debugsource~3.96~lp151.3.3.1", rls:"openSUSELeap15.1"))) {
    report += res;
  }

  if(report != "") {
    security_message(data:report);
  } else if(__pkg_match) {
    exit(99);
  }
  exit(0);
}

exit(0);
